/**
 * lib/chat.ts — Pure utility functions for the conversational task builder.
 */

export interface ChatTask {
  id: string;
  label: string;
  fixedTime?: string;
  urgency?: string;
}

/**
 * Generates a simple random ID for tasks.
 */
function generateId(): string {
  return Math.random().toString(36).substring(2, 9);
}

/**
 * Merges the AI's updated list of tasks with the previous state.
 * It attempts to preserve stable IDs by matching task labels.
 * 
 * @param prevTasks - The previous state of tasks
 * @param aiUpdatedTasks - The new array of tasks generated by the AI
 * @returns A new array of ChatTasks with stable IDs
 */
export function mergeTaskLists(
  prevTasks: ChatTask[],
  aiUpdatedTasks: Partial<ChatTask>[]
): ChatTask[] {
  // Keep track of which previous tasks we've already matched to avoid duplicate mapping
  const usedPrevIds = new Set<string>();

  return aiUpdatedTasks.map((newTask) => {
    // Find the first matching previous task by label that hasn't been used yet
    const matchingPrev = prevTasks.find(
      (pt) => pt.label === newTask.label && !usedPrevIds.has(pt.id)
    );

    if (matchingPrev) {
      usedPrevIds.add(matchingPrev.id);
      return {
        id: matchingPrev.id,
        label: newTask.label || matchingPrev.label,
        fixedTime: newTask.fixedTime,
        urgency: newTask.urgency,
      };
    }

    // If no match found, it's a new task, generate a new ID
    return {
      id: newTask.id || generateId(),
      label: newTask.label || "مهمة بدون اسم",
      fixedTime: newTask.fixedTime,
      urgency: newTask.urgency,
    };
  });
}
