/**
 * lib/schedule.ts — Pure scheduling utility functions.
 *
 * All merge/buffer/overlap logic lives here, separate from API routes
 * and React components, so it can be tested independently.
 *
 * TDD: Tests were written first (see __tests__/schedule.test.ts),
 * then this implementation was built to make them pass.
 */

// ─── Types ───────────────────────────────────────────────────────────

export interface TimeBlock {
  type: "study" | "prayer" | "sleep";
  label: string;
  startTime: string; // "HH:mm" 24-hour format
  endTime: string; // "HH:mm" 24-hour format
  sub?: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────

/**
 * Converts a "HH:mm" string to total minutes since midnight.
 * Example: "14:30" → 870
 */
export function parseTime(timeStr: string): number {
  const [h, m] = timeStr.split(":").map(Number);
  return h * 60 + m;
}

/**
 * Converts minutes since midnight back to "HH:mm" string.
 * Example: 870 → "14:30"
 */
export function minutesToTime(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}`;
}

/**
 * Checks whether blockA overlaps with blockB's buffer window.
 * The buffer extends `bufferMinutes` before blockB's start and after blockB's end.
 *
 * Two intervals [a1, a2] and [b1-buffer, b2+buffer] overlap
 * if and only if a1 < (b2 + buffer) AND a2 > (b1 - buffer).
 *
 * Returns true if there IS an overlap (meaning blockA should be removed).
 */
export function hasOverlap(
  blockA: TimeBlock,
  blockB: TimeBlock,
  bufferMinutes: number = 30
): boolean {
  const aStart = parseTime(blockA.startTime);
  const aEnd = parseTime(blockA.endTime);
  const bStart = parseTime(blockB.startTime) - bufferMinutes;
  const bEnd = parseTime(blockB.endTime) + bufferMinutes;

  // Two intervals overlap if one starts before the other ends AND vice versa
  return aStart < bEnd && aEnd > bStart;
}

// ─── Prayer Time Conversion ──────────────────────────────────────────

/** The 5 daily prayers we care about from the Aladhan API */
const PRAYER_NAMES: Record<string, string> = {
  Fajr: "أذان الفجر",
  Dhuhr: "أذان الظهر",
  Asr: "أذان العصر",
  Maghrib: "أذان المغرب",
  Isha: "أذان العشاء",
};

/** Default prayer duration in minutes */
const PRAYER_DURATION = 30;

/**
 * Cleans a time string from the Aladhan API.
 * Removes timezone suffixes like " (EET)" → "04:30 (EET)" becomes "04:30"
 */
function cleanTime(timeStr: string): string {
  return timeStr.split(" ")[0];
}

/**
 * Converts Aladhan API timings object to our TimeBlock[] format.
 * Each prayer is treated as a 30-minute block (the prayer itself).
 * Only the 5 main prayers are included (Fajr, Dhuhr, Asr, Maghrib, Isha).
 */
export function prayerTimesToBlocks(
  timings: Record<string, string>
): TimeBlock[] {
  const blocks: TimeBlock[] = [];

  for (const [key, arabicLabel] of Object.entries(PRAYER_NAMES)) {
    const rawTime = timings[key];
    if (!rawTime) continue;

    const startTime = cleanTime(rawTime);
    const startMinutes = parseTime(startTime);
    const endTime = minutesToTime(startMinutes + PRAYER_DURATION);

    blocks.push({
      type: "prayer",
      label: arabicLabel,
      startTime,
      endTime,
      sub: "فاصل ٣٠ دقيقة",
    });
  }

  // Sort by start time
  blocks.sort((a, b) => parseTime(a.startTime) - parseTime(b.startTime));

  return blocks;
}

// ─── Core Merge Logic ────────────────────────────────────────────────

/**
 * Merges AI-generated study blocks with prayer time blocks.
 *
 * Rules:
 * 1. Prayer blocks are ALWAYS preserved (never filtered out)
 * 2. Study/sleep blocks that overlap any prayer's buffer window are REMOVED
 * 3. The buffer window is `bufferMinutes` before AND after each prayer block
 * 4. The returned array is sorted by startTime ascending
 *
 * @param aiBlocks   - Study/sleep blocks generated by the AI
 * @param prayerTimes - Prayer time blocks from prayerTimesToBlocks()
 * @param bufferMinutes - Buffer before/after each prayer (default: 30)
 * @returns Merged, sorted, conflict-free timeline
 */
export function mergeScheduleWithPrayerTimes(
  aiBlocks: TimeBlock[],
  prayerTimes: TimeBlock[],
  bufferMinutes: number = 30
): TimeBlock[] {
  // Filter out AI blocks that overlap any prayer's buffer window
  const safeBlocks = aiBlocks.filter((aiBlock) => {
    // Check against every prayer time
    return !prayerTimes.some((prayer) =>
      hasOverlap(aiBlock, prayer, bufferMinutes)
    );
  });

  // Combine safe AI blocks with all prayer blocks
  const merged = [...safeBlocks, ...prayerTimes];

  // Sort by startTime ascending
  merged.sort((a, b) => parseTime(a.startTime) - parseTime(b.startTime));

  return merged;
}
